version: '3'
services:
    mqtt:
        image: emqx/emqx
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: always
        network_mode: "host"
        ports:
            - 18083:18083
            - 1883:1883
            - 8084:8084
            - 8883:8883
            - 8083:8083