version: '3'
services:
    mqtt:
        image: eclipse-mosquitto:latest
        container_name: mqtt
        privileged: true
        restart: always
        ports: 
            - 1883:1883
            #- 8000:8000 # 需要使用 websockets 的话
            #- 9001:9001
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
