version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
        - 5432:5432
    volumes:
        - /data/postgresql:/var/lib/postgresql/data