version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: mysql
    volumes:
      - /data/mysql/mydir:/mydir
      - /data/mysql/datadir:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
      #  数据库还原目录 可将需要还原的sql文件放在这里
      - /data/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=123456"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306