version: '3.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9003:9000"
      - "9004:9001"
    restart: always
    command: server /data -console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123 #大于等于8位
    logging:
      options:
        max-size: "50M" # 最大文件上传限制
        max-file: "10"
      driver: json-file
    volumes:
      - /data/minio:/data # 映射文件路径