version: '3.0'
services:
  minio:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=bluefrog
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=grafana
      - DOCKER_INFLUXDB_INIT_BUCKET=grafana
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=grafana
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      - INFLUXD_CONFIG_PATH=/etc/influxdb2
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2